import { Station } from '@/types';

/**
 * Mock station data for Dhaka, Bangladesh
 * These are real fuel station locations in Dhaka area
 */
export const MOCK_STATIONS: Station[] = [
  {
    id: '1',
    name: 'Petrobangla Fuel Station',
    address: 'Kakrail, Dhaka',
    lat: 23.7350,
    lng: 90.4145,
    status: 'available',
    confidence: 92,
    last_reported_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    last_reporter_id: 'user-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Bangladesh Petroleum Corp',
    address: 'Mohammadpur, Dhaka',
    lat: 23.7620,
    lng: 90.3650,
    status: 'low',
    confidence: 78,
    last_reported_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    last_reporter_id: 'user-2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Jamuna Fuel Station',
    address: 'Gulshan-1, Dhaka',
    lat: 23.7925,
    lng: 90.4083,
    status: 'queue',
    confidence: 85,
    last_reported_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    last_reporter_id: 'user-3',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Padma Fuel Station',
    address: 'Uttara Sector 3, Dhaka',
    lat: 23.8738,
    lng: 90.3974,
    status: 'empty',
    confidence: 95,
    last_reported_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    last_reporter_id: 'user-4',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Mymensingh Road Fuel',
    address: 'Mirpur-10, Dhaka',
    lat: 23.8015,
    lng: 90.3667,
    status: 'available',
    confidence: 88,
    last_reported_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    last_reporter_id: 'user-5',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Modhumati Fuel Station',
    address: 'Dhanmondi 27, Dhaka',
    lat: 23.7467,
    lng: 90.3789,
    status: 'unknown',
    confidence: 0,
    last_reported_at: null,
    last_reporter_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Meghna Petroleum',
    address: 'Farmgate, Dhaka',
    lat: 23.7589,
    lng: 90.3878,
    status: 'low',
    confidence: 65,
    last_reported_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    last_reporter_id: 'user-7',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Shahjalal Fuel Center',
    address: 'Motiijheel, Dhaka',
    lat: 23.7233,
    lng: 90.4217,
    status: 'available',
    confidence: 90,
    last_reported_at: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    last_reporter_id: 'user-8',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Rasulpur Fuel Station',
    address: 'Banani, Dhaka',
    lat: 23.7933,
    lng: 90.4011,
    status: 'queue',
    confidence: 72,
    last_reported_at: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    last_reporter_id: 'user-9',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Chittagong Road Fuel',
    address: 'Tejgaon, Dhaka',
    lat: 23.7783,
    lng: 90.3933,
    status: 'empty',
    confidence: 98,
    last_reported_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    last_reporter_id: 'user-10',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_USER_ID = 'mock-user-001';
export const MOCK_USER_LAT = 23.8103; // Dhaka center
export const MOCK_USER_LNG = 90.4125;
